import { AdminTable, AdminTd, AdminTh, AdminTr } from "components/admin-table";
import { Heading } from "components/heading";


const HeadingStyle = {
    textAlign:"left"
}

export default function ViewOrderPage () {
    return(
        <>
        <Heading style={HeadingStyle}>
            Orders
        </Heading>
        <AdminTable>
            <thead>
               <AdminTr>
               <AdminTh>
                    Order ID
                </AdminTh>
                <AdminTh>
                    Product
                </AdminTh>
                <AdminTh>
                    Size
                </AdminTh>
                <AdminTh>
                    Amount
                </AdminTh>
                <AdminTh>
                    Price
                </AdminTh>
                <AdminTh>
                    Customer
                </AdminTh>
                <AdminTh>
                    Date Income
                </AdminTh>
                <AdminTh>
                    Action
                </AdminTh>
               </AdminTr>
            </thead>
            <tbody>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
               <AdminTr>
               <AdminTd>
                    19201
                </AdminTd>
                <AdminTd>
                    Apple Cinema 30
                </AdminTd>
                <AdminTd>
                    5
                </AdminTd>
                <AdminTd>
                    345
                </AdminTd>
                <AdminTd>
                    $560
                </AdminTd>
                <AdminTd>
                    John Doe
                </AdminTd>
                <AdminTd>
                    09/04/2022
                </AdminTd>
                <AdminTd>
                    Edit
                </AdminTd>
               </AdminTr>
            </tbody>
        </AdminTable>
        </>
    )
}